#!/usr/bin/env python3
"""Write complete deterministic PilotTrace JSON examples without dependencies."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"


def main() -> None:
    EXAMPLES.mkdir(exist_ok=True)
    quiet = [0.0] * 512
    burst = [0.0] * 512
    burst[:32] = [1.0] * 32
    trace = {
        "frames": [
            {"values": quiet, "label": False},
            {"values": burst, "label": True},
        ]
    }
    manifest = {
        "schema_version": 1,
        "threshold": 0.5,
        "channel_order": (
            "Values are in the caller's declared index order 0 through 511; block 0 is "
            "indices 0–31, continuing in contiguous groups of 32."
        ),
        "units": "dimensionless synthetic amplitude units",
        "scaling": "Values are used as supplied; PilotTrace applies no additional scaling.",
        "timebase": (
            "Frame order is the only time axis; one frame is one synthetic step and no "
            "elapsed-time rate is asserted."
        ),
        "baseline_preprocessing": (
            "Zero is the illustrative baseline; no normalization, filtering, or baseline "
            "correction is applied."
        ),
        "missing_value_policy": (
            "A frame with a missing, non-numeric, NaN, or infinite channel is rejected; "
            "no imputation is performed."
        ),
        "source_provenance": (
            "Deterministic local example data generated by tools/make_example.py."
        ),
        "permitted_use": (
            "Offline software and schema demonstration only; not operational monitoring, "
            "safety, medical, or control use."
        ),
    }
    (EXAMPLES / "sample_trace.json").write_text(
        json.dumps(trace, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (EXAMPLES / "sample_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote examples to {EXAMPLES}")


if __name__ == "__main__":
    main()
